version: '3.8'

services:

  simplewebapp:
    container_name: 'simplewebapp'
    build: '.'
    ports:
      - 8080
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: employeedb
    volumes:
      - ./docker/volumes/postgres:/var/lib/postgresql/
    ports:
      - 5432:5432