version: '3.8'

services:

  simplewebapp:
    container_name: 'simplewebapp'
    build: '.'
    ports:
      - 8080
  db:
    image: postgres
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa
      POSTGRES_DB: simplewebapp
#    volumes:
#      - ./docker/volumes/postgres:/var/lib/postgresql/data postgres
    ports:
      - 5432:5432